### ISSUE TITLE
Yahoo Webscope S5 dataset

### ISSUE THREAD

**Issue by 6GOnline** [wadieskaf/denoising_architecture_time_series_paper#1]
Hello author, can you share this dataset（Yahoo Webscope S5 dataset）? Thank you very much !

**Comment by skafai** [comment]
> Hello author, can you share this dataset（Yahoo Webscope S5 dataset）? Thank you very much !

There is a link in the `README` file, please refer to it. The data has to be requested from Yahoo and I don't have the permission to share it in my repo.
